CREATE TABLE dares (
    dare_id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    dare_text TEXT NOT NULL,
    added_by TEXT,
    seen INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)